lkl: Define symbols for string utilities
The generated lkl.o currently still directly references string utility
symbols (e.g., memcpy and memset). This is because some kernel sources
use things like __builtin_memcpy and the compiler generates a direct
call to the memcpy method.

	$ ld -o lkl lkl.o
	[ .. ]
	lkl.o: in function `virtblk_probe':
	drivers/block/virtio_blk.c:1367:(.text+0xa6c6be): undefined reference to `memset'
	lkl.o: in function `virtblk_name_format':
	drivers/block/virtio_blk.c:1125:(.text+0xa6c97a): undefined reference to `memmove'
	drivers/block/virtio_blk.c:1126:(.text+0xa6c99c): undefined reference to `memcpy'
	[ .. ]

I suspect this isn't really expected, since LKL shouldn't reference the
memcpy symbol directly, it should try to do so via host_ops first (i.e.,
make a call to lkl_ops->memcpy).

The reason is that we claim __HAVE_ARCH_MEMCPY, but we don't actually
provide the memcpy symbol. We should do that. This commit follows much
the same approach as the x86 architecture, see arch/x86/lib/memcpy_32.c
for the reference.

Signed-off-by: Ruihan Li <lrh2000@pku.edu.cn>